import type { ComponentRegistryItem, DomainCategory } from "../schema"

function item(
  partial: Omit<ComponentRegistryItem, "displayImportPath"> & {
    displayImportPath?: ComponentRegistryItem["displayImportPath"]
  }
): ComponentRegistryItem {
  return {
    ...partial,
    displayImportPath: partial.displayImportPath ?? {
      kind: "local",
      value: partial.internalImportPath,
    },
  }
}

/** Pilot registry: Chamaac components with verified source-registry mappings. */
export const CHAMAAC_REGISTRY: ComponentRegistryItem[] = [
  item({
    id: "chamaac/nebula",
    catalogId: "nebula",
    title: "星云",
    titleEn: "Nebula",
    category: "effects",
    docsSlug: "effects/backgrounds/nebula",
    files: [{ path: "src/components/effects/backgrounds/nebula/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/nebula",
    legacyShellImportPath: "@/components/core/nebula",
  }),
  item({
    id: "chamaac/electric-mist",
    catalogId: "electric-mist",
    title: "电雾",
    titleEn: "ElectricMist",
    category: "effects",
    docsSlug: "effects/backgrounds/electric-mist",
    files: [{ path: "src/components/effects/backgrounds/electric-mist/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/electric-mist",
    legacyShellImportPath: "@/components/core/electric-mist",
  }),
  item({
    id: "chamaac/grid-bloom",
    catalogId: "grid-bloom",
    title: "网格绽放",
    titleEn: "GridBloom",
    category: "effects",
    docsSlug: "effects/backgrounds/grid-bloom",
    files: [{ path: "src/components/effects/backgrounds/grid-bloom/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/grid-bloom",
    legacyShellImportPath: "@/components/core/grid-bloom",
  }),
  item({
    id: "chamaac/liquid-morph",
    catalogId: "liquid-morph",
    title: "液态变形",
    titleEn: "LiquidMorph",
    category: "effects",
    docsSlug: "effects/backgrounds/liquid-morph",
    files: [{ path: "src/components/effects/backgrounds/liquid-morph/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/liquid-morph",
    legacyShellImportPath: "@/components/core/liquid-morph",
  }),
  item({
    id: "chamaac/emissive-dot-grid",
    catalogId: "emissive-dot-grid",
    title: "发光点阵",
    titleEn: "EmissiveDotGrid",
    category: "effects",
    docsSlug: "effects/backgrounds/emissive-dot-grid",
    files: [{ path: "src/components/effects/backgrounds/emissive-dot-grid/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/emissive-dot-grid",
    legacyShellImportPath: "@/components/core/emissive-dot-grid",
  }),
  item({
    id: "chamaac/iridescent-windows",
    catalogId: "iridescent-windows",
    title: "彩虹窗口",
    titleEn: "IridescentWindows",
    category: "effects",
    docsSlug: "effects/backgrounds/iridescent-windows",
    files: [{ path: "src/components/effects/backgrounds/iridescent-windows/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/iridescent-windows",
    legacyShellImportPath: "@/components/core/iridescent-windows",
  }),
  item({
    id: "chamaac/water-caustic",
    catalogId: "water-caustic",
    title: "水焦散",
    titleEn: "WaterCaustic",
    category: "effects",
    docsSlug: "effects/backgrounds/water-caustic",
    files: [{ path: "src/components/effects/backgrounds/water-caustic/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/water-caustic",
    legacyShellImportPath: "@/components/core/water-caustic",
  }),
  item({
    id: "chamaac/dancing-letters",
    catalogId: "dancing-letters",
    title: "舞动字母",
    titleEn: "DancingLetters",
    category: "effects",
    docsSlug: "effects/text/dancing-letters",
    files: [{ path: "src/components/effects/text/dancing-letters/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/dancing-letters",
    legacyShellImportPath: "@/components/core/dancing-letters",
  }),
  item({
    id: "chamaac/text-loop",
    catalogId: "text-loop",
    title: "文字循环",
    titleEn: "TextLoop",
    category: "effects",
    docsSlug: "effects/text/text-loop",
    files: [{ path: "src/components/effects/text/text-loop/index.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/text-loop",
    legacyShellImportPath: "@/components/core/text-loop",
  }),
  item({
    id: "chamaac/gauge",
    catalogId: "gauge",
    title: "仪表盘",
    titleEn: "Gauge",
    category: "charts",
    docsSlug: "charts/gauge-chamaac/gauge",
    files: [{ path: "src/components/charts/gauge-chamaac/gauge.tsx", role: "source" }],
    internalImportPath: "@/components/charts/gauge-chamaac/gauge",
    legacyShellImportPath: "@/components/core/gauge-chamaac",
  }),
  item({
    id: "chamaac/shimmer-button",
    catalogId: "shimmer-button",
    title: "闪光按钮",
    titleEn: "ShimmerButton",
    category: "general",
    docsSlug: "general/shimmer-button",
    files: [{ path: "src/components/general/shimmer-button/index.tsx", role: "source" }],
    internalImportPath: "@/components/general/shimmer-button",
    legacyShellImportPath: "@/components/core/shimmer-button",
  }),
  item({
    id: "chamaac/feature-steps",
    catalogId: "feature-steps",
    title: "特性步骤",
    titleEn: "FeatureSteps",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/feature-steps",
    files: [{ path: "src/components/marketing-blocks/feature-steps/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/feature-steps",
    legacyShellImportPath: "@/components/core/feature-steps",
  }),
  item({
    id: "chamaac/carousel",
    catalogId: "carousel",
    title: "轮播",
    titleEn: "Carousel",
    category: "data-display",
    docsSlug: "data-display/carousel",
    files: [{ path: "src/components/data-display/carousel/index.tsx", role: "source" }],
    internalImportPath: "@/components/data-display/carousel",
    legacyShellImportPath: "@/components/core/carousel-chamaac",
  }),
]

/** Pilot registry: GooseUI components with verified source-registry mappings. */
export const GOOSEUI_REGISTRY: ComponentRegistryItem[] = [
  item({
    id: "gooseui/border-beam",
    catalogId: "border-beam",
    title: "边框光束",
    titleEn: "BorderBeam",
    category: "effects",
    docsSlug: "effects/interactions/border-beam",
    files: [{ path: "src/components/effects/interactions/border-beam.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/border-beam",
    legacyShellImportPath: "@/components/core/border-beam-gooseui",
  }),
  item({
    id: "gooseui/curved-text",
    catalogId: "curved-text",
    title: "曲线文字",
    titleEn: "CurvedText",
    category: "effects",
    docsSlug: "effects/text/curved-text",
    files: [{ path: "src/components/effects/text/curved-text.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/curved-text",
    legacyShellImportPath: "@/components/core/curved-text",
  }),
  item({
    id: "gooseui/stacking-cards",
    catalogId: "stacking-cards",
    title: "堆叠卡片",
    titleEn: "StackingCards",
    category: "effects",
    docsSlug: "effects/interactions/stacking-cards",
    files: [{ path: "src/components/effects/interactions/stacking-cards.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/stacking-cards",
    legacyShellImportPath: "@/components/core/stacking-cards",
  }),
  item({
    id: "gooseui/parallax-cards",
    catalogId: "parallax-cards",
    title: "视差卡片",
    titleEn: "ParallaxCards",
    category: "effects",
    docsSlug: "effects/interactions/parallax-cards",
    files: [{ path: "src/components/effects/interactions/parallax-cards.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/parallax-cards",
    legacyShellImportPath: "@/components/core/parallax-cards",
  }),
  item({
    id: "gooseui/promo-banner",
    catalogId: "promo-banner",
    title: "促销横幅",
    titleEn: "PromoBanner",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/promo-banner",
    files: [{ path: "src/components/marketing-blocks/promo-banner.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/promo-banner",
    legacyShellImportPath: "@/components/core/promo-banner",
  }),
  item({
    id: "gooseui/features-grid",
    catalogId: "features-grid",
    title: "特性网格",
    titleEn: "FeaturesGrid",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/features-grid",
    files: [{ path: "src/components/marketing-blocks/features-grid/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/features-grid",
    legacyShellImportPath: "@/components/core/features-grid",
  }),
  item({
    id: "gooseui/footer-columns",
    catalogId: "footer-columns",
    title: "多列页脚",
    titleEn: "FooterColumns",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/footer-columns",
    files: [{ path: "src/components/marketing-blocks/footer-columns/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/footer-columns",
    legacyShellImportPath: "@/components/core/footer-columns",
  }),
  item({
    id: "gooseui/footer-simple",
    catalogId: "footer-simple",
    title: "简单页脚",
    titleEn: "FooterSimple",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/footer-simple",
    files: [{ path: "src/components/marketing-blocks/footer-simple/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/footer-simple",
    legacyShellImportPath: "@/components/core/footer-simple",
  }),
  item({
    id: "gooseui/footer-newsletter",
    catalogId: "footer-newsletter",
    title: "订阅页脚",
    titleEn: "FooterNewsletter",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/footer-newsletter",
    files: [{ path: "src/components/marketing-blocks/footer-newsletter/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/footer-newsletter",
    legacyShellImportPath: "@/components/core/footer-newsletter",
  }),
  item({
    id: "gooseui/curved-text-marquee",
    catalogId: "curved-text-marquee",
    title: "曲线文字跑马灯",
    titleEn: "CurvedTextMarquee",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/curved-text-marquee",
    files: [{ path: "src/components/marketing-blocks/curved-text-marquee/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/curved-text-marquee",
    legacyShellImportPath: "@/components/core/curved-text-marquee",
  }),
  item({
    id: "gooseui/header-with-cta",
    catalogId: "header-with-cta",
    title: "带 CTA 页头",
    titleEn: "HeaderWithCta",
    category: "marketing-blocks",
    docsSlug: "marketing-blocks/header-with-cta",
    files: [{ path: "src/components/marketing-blocks/header-with-cta/index.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/header-with-cta",
    legacyShellImportPath: "@/components/core/header-with-cta",
  }),
]

export function inferCategoryFromPath(path: string): DomainCategory {
  const segment = path.split("/")[2] as DomainCategory | undefined
  const valid: DomainCategory[] = [
    "effects",
    "charts",
    "media",
    "editor",
    "document",
    "agent-tools",
    "marketing-blocks",
    "templates",
    "general",
    "layout",
    "navigation",
    "data-entry",
    "data-display",
    "feedback",
    "blocks",
    "ui",
    "_internal",
  ]
  if (segment && valid.includes(segment)) {
    return segment
  }
  return "ui"
}
