"use client"

import { Audio } from "@/components/ui/audio"

export default function Demo() {
  return (
    <Audio
      id="demo-audio"
      assetId="demo-audio-asset"
      src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
      title="SoundHelix Song 1"
      description="A sample audio track generated by SoundHelix."
      artwork="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.png"
      durationMs={240000}
      locale="zh-CN"
      source={{
        label: "SoundHelix",
        url: "https://www.soundhelix.com",
      }}
    />
  )
}
