import type { ComponentRegistryItem, DomainCategory } from "../schema"

function item(
  partial: Omit<ComponentRegistryItem, "displayImportPath"> & {
    displayImportPath?: ComponentRegistryItem["displayImportPath"]
  }
): ComponentRegistryItem {
  return {
    ...partial,
    displayImportPath: partial.displayImportPath ?? {
      kind: "local",
      value: partial.internalImportPath,
    },
  }
}

/** Pilot registry: Chamaac components with verified source-registry mappings. */
export const CHAMAAC_REGISTRY: ComponentRegistryItem[] = [
  item({
    id: "chamaac/nebula",
    catalogId: "nebula",
    title: "星云",
    titleEn: "Nebula",
    category: "effects",
    docsSlug: "chamaac/nebula",
    files: [{ path: "src/components/effects/backgrounds/chamaac/nebula/nebula.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/nebula/nebula",
    legacyShellImportPath: "@/components/ui/nebula",
  }),
  item({
    id: "chamaac/electric-mist",
    catalogId: "electric-mist",
    title: "电雾",
    titleEn: "ElectricMist",
    category: "effects",
    docsSlug: "chamaac/electric-mist",
    files: [{ path: "src/components/effects/backgrounds/chamaac/electric-mist/electric-mist.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/electric-mist/electric-mist",
    legacyShellImportPath: "@/components/ui/electric-mist",
  }),
  item({
    id: "chamaac/grid-bloom",
    catalogId: "grid-bloom",
    title: "网格绽放",
    titleEn: "GridBloom",
    category: "effects",
    docsSlug: "chamaac/grid-bloom",
    files: [{ path: "src/components/effects/backgrounds/chamaac/grid-bloom/grid-bloom.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/grid-bloom/grid-bloom",
    legacyShellImportPath: "@/components/ui/grid-bloom",
  }),
  item({
    id: "chamaac/liquid-morph",
    catalogId: "liquid-morph",
    title: "液态变形",
    titleEn: "LiquidMorph",
    category: "effects",
    docsSlug: "chamaac/liquid-morph",
    files: [{ path: "src/components/effects/backgrounds/chamaac/liquid-morph/liquid-morph.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/liquid-morph/liquid-morph",
    legacyShellImportPath: "@/components/ui/liquid-morph",
  }),
  item({
    id: "chamaac/emissive-dot-grid",
    catalogId: "emissive-dot-grid",
    title: "发光点阵",
    titleEn: "EmissiveDotGrid",
    category: "effects",
    docsSlug: "chamaac/emissive-dot-grid",
    files: [{ path: "src/components/effects/backgrounds/chamaac/emissive-dot-grid/emissive-dot-grid.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/emissive-dot-grid/emissive-dot-grid",
    legacyShellImportPath: "@/components/ui/emissive-dot-grid",
  }),
  item({
    id: "chamaac/iridescent-windows",
    catalogId: "iridescent-windows",
    title: "彩虹窗口",
    titleEn: "IridescentWindows",
    category: "effects",
    docsSlug: "chamaac/iridescent-windows",
    files: [{ path: "src/components/effects/backgrounds/chamaac/iridescent-windows/iridescent-windows.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/iridescent-windows/iridescent-windows",
    legacyShellImportPath: "@/components/ui/iridescent-windows",
  }),
  item({
    id: "chamaac/water-caustic",
    catalogId: "water-caustic",
    title: "水焦散",
    titleEn: "WaterCaustic",
    category: "effects",
    docsSlug: "chamaac/water-caustic",
    files: [{ path: "src/components/effects/backgrounds/chamaac/water-caustic/water-caustic.tsx", role: "source" }],
    internalImportPath: "@/components/effects/backgrounds/chamaac/water-caustic/water-caustic",
    legacyShellImportPath: "@/components/ui/water-caustic",
  }),
  item({
    id: "chamaac/dancing-letters",
    catalogId: "dancing-letters",
    title: "舞动字母",
    titleEn: "DancingLetters",
    category: "effects",
    docsSlug: "chamaac/dancing-letters",
    files: [{ path: "src/components/effects/text/chamaac/dancing-letters/dancing-letters.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/chamaac/dancing-letters/dancing-letters",
    legacyShellImportPath: "@/components/ui/dancing-letters",
  }),
  item({
    id: "chamaac/text-loop",
    catalogId: "text-loop",
    title: "文字循环",
    titleEn: "TextLoop",
    category: "effects",
    docsSlug: "chamaac/text-loop",
    files: [{ path: "src/components/effects/text/chamaac/text-loop/text-loop.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/chamaac/text-loop/text-loop",
    legacyShellImportPath: "@/components/ui/text-loop",
  }),
  item({
    id: "chamaac/gauge",
    catalogId: "gauge",
    title: "仪表盘",
    titleEn: "Gauge",
    category: "charts",
    docsSlug: "chamaac/gauge",
    files: [{ path: "src/components/charts/chamaac/gauge/gauge.tsx", role: "source" }],
    internalImportPath: "@/components/charts/chamaac/gauge/gauge",
    legacyShellImportPath: "@/components/ui/gauge-chamaac",
  }),
  item({
    id: "chamaac/shimmer-button",
    catalogId: "shimmer-button",
    title: "闪光按钮",
    titleEn: "ShimmerButton",
    category: "general",
    docsSlug: "chamaac/shimmer-button",
    files: [{ path: "src/components/general/chamaac/shimmer-button/shimmer-button.tsx", role: "source" }],
    internalImportPath: "@/components/general/chamaac/shimmer-button/shimmer-button",
    legacyShellImportPath: "@/components/ui/shimmer-button",
  }),
  item({
    id: "chamaac/feature-steps",
    catalogId: "feature-steps",
    title: "特性步骤",
    titleEn: "FeatureSteps",
    category: "marketing-blocks",
    docsSlug: "chamaac/feature-steps",
    files: [{ path: "src/components/marketing-blocks/chamaac/feature-steps/feature-steps.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/chamaac/feature-steps/feature-steps",
    legacyShellImportPath: "@/components/ui/feature-steps",
  }),
  item({
    id: "chamaac/carousel",
    catalogId: "carousel",
    title: "轮播",
    titleEn: "Carousel",
    category: "data-display",
    docsSlug: "chamaac/carousel",
    files: [{ path: "src/components/data-display/chamaac/carousel/carousel.tsx", role: "source" }],
    internalImportPath: "@/components/data-display/chamaac/carousel/carousel",
    legacyShellImportPath: "@/components/ui/carousel-chamaac",
  }),
]

/** Pilot registry: GooseUI components with verified source-registry mappings. */
export const GOOSEUI_REGISTRY: ComponentRegistryItem[] = [
  item({
    id: "gooseui/border-beam",
    catalogId: "border-beam",
    title: "边框光束",
    titleEn: "BorderBeam",
    category: "effects",
    docsSlug: "gooseui/border-beam",
    files: [{ path: "src/components/effects/interactions/gooseui/border-beam.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/gooseui/border-beam",
    legacyShellImportPath: "@/components/ui/border-beam-gooseui",
  }),
  item({
    id: "gooseui/curved-text",
    catalogId: "curved-text",
    title: "曲线文字",
    titleEn: "CurvedText",
    category: "effects",
    docsSlug: "gooseui/curved-text",
    files: [{ path: "src/components/effects/text/gooseui/curved-text.tsx", role: "source" }],
    internalImportPath: "@/components/effects/text/gooseui/curved-text",
    legacyShellImportPath: "@/components/ui/curved-text",
  }),
  item({
    id: "gooseui/stacking-cards",
    catalogId: "stacking-cards",
    title: "堆叠卡片",
    titleEn: "StackingCards",
    category: "effects",
    docsSlug: "gooseui/stacking-cards",
    files: [{ path: "src/components/effects/interactions/gooseui/stacking-cards.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/gooseui/stacking-cards",
    legacyShellImportPath: "@/components/ui/stacking-cards",
  }),
  item({
    id: "gooseui/parallax-cards",
    catalogId: "parallax-cards",
    title: "视差卡片",
    titleEn: "ParallaxCards",
    category: "effects",
    docsSlug: "gooseui/parallax-cards",
    files: [{ path: "src/components/effects/interactions/gooseui/parallax-cards.tsx", role: "source" }],
    internalImportPath: "@/components/effects/interactions/gooseui/parallax-cards",
    legacyShellImportPath: "@/components/ui/parallax-cards",
  }),
  item({
    id: "gooseui/promo-banner",
    catalogId: "promo-banner",
    title: "促销横幅",
    titleEn: "PromoBanner",
    category: "marketing-blocks",
    docsSlug: "gooseui/promo-banner",
    files: [{ path: "src/components/marketing-blocks/gooseui/promo-banner.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/promo-banner",
    legacyShellImportPath: "@/components/ui/promo-banner",
  }),
  item({
    id: "gooseui/features-grid",
    catalogId: "features-grid",
    title: "特性网格",
    titleEn: "FeaturesGrid",
    category: "marketing-blocks",
    docsSlug: "gooseui/features-grid",
    files: [{ path: "src/components/marketing-blocks/gooseui/features/features-grid.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/features/features-grid",
    legacyShellImportPath: "@/components/ui/features-grid",
  }),
  item({
    id: "gooseui/footer-columns",
    catalogId: "footer-columns",
    title: "多列页脚",
    titleEn: "FooterColumns",
    category: "marketing-blocks",
    docsSlug: "gooseui/footer-columns",
    files: [{ path: "src/components/marketing-blocks/gooseui/footers/footer-columns.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/footers/footer-columns",
    legacyShellImportPath: "@/components/ui/footer-columns",
  }),
  item({
    id: "gooseui/footer-simple",
    catalogId: "footer-simple",
    title: "简单页脚",
    titleEn: "FooterSimple",
    category: "marketing-blocks",
    docsSlug: "gooseui/footer-simple",
    files: [{ path: "src/components/marketing-blocks/gooseui/footers/footer-simple.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/footers/footer-simple",
    legacyShellImportPath: "@/components/ui/footer-simple",
  }),
  item({
    id: "gooseui/footer-newsletter",
    catalogId: "footer-newsletter",
    title: "订阅页脚",
    titleEn: "FooterNewsletter",
    category: "marketing-blocks",
    docsSlug: "gooseui/footer-newsletter",
    files: [{ path: "src/components/marketing-blocks/gooseui/footers/footer-newsletter.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/footers/footer-newsletter",
    legacyShellImportPath: "@/components/ui/footer-newsletter",
  }),
  item({
    id: "gooseui/curved-text-marquee",
    catalogId: "curved-text-marquee",
    title: "曲线文字跑马灯",
    titleEn: "CurvedTextMarquee",
    category: "marketing-blocks",
    docsSlug: "gooseui/curved-text-marquee",
    files: [{ path: "src/components/marketing-blocks/gooseui/marketing/curved-text-marquee.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/marketing/curved-text-marquee",
    legacyShellImportPath: "@/components/ui/curved-text-marquee",
  }),
  item({
    id: "gooseui/header-with-cta",
    catalogId: "header-with-cta",
    title: "带 CTA 页头",
    titleEn: "HeaderWithCta",
    category: "marketing-blocks",
    docsSlug: "gooseui/header-with-cta",
    files: [{ path: "src/components/marketing-blocks/gooseui/headers/header-with-cta.tsx", role: "source" }],
    internalImportPath: "@/components/marketing-blocks/gooseui/headers/header-with-cta",
    legacyShellImportPath: "@/components/ui/header-with-cta",
  }),
]

export function inferCategoryFromPath(path: string): DomainCategory {
  const segment = path.split("/")[2] as DomainCategory | undefined
  const valid: DomainCategory[] = [
    "effects",
    "charts",
    "media",
    "editor",
    "document",
    "agent-tools",
    "marketing-blocks",
    "templates",
    "general",
    "layout",
    "navigation",
    "data-entry",
    "data-display",
    "feedback",
    "blocks",
    "ui",
    "_shared",
  ]
  if (segment && valid.includes(segment)) {
    return segment
  }
  return "ui"
}
