export type GalleryNavItem = {
  id: string
  label: string
  en: string
  to: string
  summary: string
  keywords: string[]
  /** 是否有 Ant Design 对应组件 */
  antd?: boolean
  /** Ant Design API 迁移覆盖率 (0-100) */
  migration?: number
  /** 是否具有单入口 props 驱动的 API（非 compound/composition 模式） */
  api?: boolean
}

export type GalleryNavGroup = {
  group: string
  groupEn: string
  items: GalleryNavItem[]
  libraryId?: string
}

export type GalleryTocItem = {
  id: string
  title: string
  depth: 2 | 3
}

export type GalleryDocMeta = {
  title: string
  en: string
  description: string
  toc: GalleryTocItem[]
}

type ComponentSeed = {
  id: string
  en: string
  label: string
  summary?: string
  keywords?: string[]
  /** 是否有 Ant Design 对应组件。默认根据 id 自动判断 */
  antd?: boolean
  /** Ant Design API 迁移覆盖率 (0-100)。有 antd 映射时默认 90 */
  migration?: number
  /** 是否具有单入口 props 驱动的 API（非 compound/composition 模式） */
  api?: boolean
}

function uselayoutsItem(id: string, en: string, label: string): GalleryNavItem {
  return {
    id,
    label,
    en,
    to: `/components/uselayouts/${id}`,
    summary: `${label}，UseLayouts 布局组件。`,
    keywords: [id, en, en.toLowerCase(), label],
    antd: false,
    migration: 0,
    api: true,
  }
}

function sabramanItem(id: string, en: string, label: string): GalleryNavItem {
  return {
    id,
    label,
    en,
    to: `/components/sabraman/${id}`,
    summary: `${label}，Sabraman 组件。`,
    keywords: [id, en, en.toLowerCase(), label],
    antd: false,
    migration: 0,
    api: true,
  }
}

function evilItem(id: string, en: string, label: string): GalleryNavItem {
  return {
    id,
    label,
    en,
    to: `/components/evilcharts/${id}`,
    summary: `${label}，EvilCharts 图表组件。`,
    keywords: [id, en, en.toLowerCase(), label],
    antd: false,
    migration: 0,
    api: true,
  }
}

function bklitItem(id: string, en: string, label: string): GalleryNavItem {
  return {
    id,
    label,
    en,
    to: `/components/bklit/${id}`,
    summary: `${label}，BKLit 图表组件。`,
    keywords: [id, en, en.toLowerCase(), label],
    antd: false,
    migration: 0,
    api: true,
  }
}

function rbItem(id: string, en: string, label: string): GalleryNavItem {
  return {
    id,
    label,
    en,
    to: `/components/rb/${id}`,
    summary: `${label}，React Bits 组件。`,
    keywords: [id, en, en.toLowerCase(), label],
    antd: false,
    migration: 0,
    api: true,
  }
}

/** 无 Ant Design 对应组件的 id 列表 */
const NON_ANTD_IDS = new Set([
  "accordion", "alert-dialog", "announcement", "aspect-ratio", "attachment",
  "avatar-stack", "avatar-tooltip-group", "banner", "button-group", "calculator",
  "chart", "chat-bubble", "choicebox", "code-block", "code-panel", "code-tabs",
  "combobox", "command", "comparison", "context-menu", "contribution-graph",
  "copy-button", "credit-card", "cursor-follow", "data-table", "deck",
  "dialog-stack", "direction", "dropzone", "editor", "feature-calendar",
  "file-tree", "gantt", "github-stars-wheel", "glimpse", "hover-card",
  "image-crop", "image-zoom", "input-group", "kanban", "kbd", "label",
  "link-preview", "list-item", "marker", "marquee",
  "message-scroller", "mini-calendar", "native-select", "notification-api",
  "pill", "plate-editors-showcase", "presence-cursor", "rating", "reel",
  "relative-time", "resizable", "sandbox", "scroll-area", "separator",
  "sheet", "sidebar", "snippet", "spinner", "status", "stories",
  "tabs-motion", "tags", "theme-switcher", "ticker", "toaster", "toggle",
  "toggle-group", "tooltip-motion", "video-player",
  "mdx-test",
])

/** 复杂组件的迁移覆盖率略低 */
const MIGRATION_OVERRIDES: Record<string, number> = {
  "date-picker": 85,
  dialog: 85,
  "form-field": 85,
  menubar: 85,
  "navigation-menu": 85,
  table: 85,
  transfer: 80,
  tree: 85,
  "tree-select": 85,
  cascader: 85,
  mentions: 85,
  "color-picker": 90,
  calendar: 90,
  carousel: 90,
  "dropdown-menu": 90,
  "float-button": 90,
  pagination: 90,
  select: 90,
  slider: 90,
  tabs: 90,
}

function resolveAntd(id: string): { antd: boolean; migration: number } {
  if (NON_ANTD_IDS.has(id)) return { antd: false, migration: 0 }
  const migration = MIGRATION_OVERRIDES[id] ?? 95
  return { antd: true, migration }
}

function componentItem({
  id,
  en,
  label,
  summary,
  keywords = [],
  antd,
  migration,
  api,
}: ComponentSeed): GalleryNavItem {
  const resolved = antd !== undefined
    ? { antd, migration: migration ?? (antd ? 90 : 0) }
    : resolveAntd(id)

  return {
    id,
    label,
    en,
    to: `/components/${id}`,
    summary: summary ?? `${label}，对齐 Ant Design ${en} 的组件用法。`,
    keywords: [id, en, en.toLowerCase(), label, ...keywords],
    antd: resolved.antd,
    migration: resolved.migration,
    api,
  }
}

export const GALLERY_NAV_GROUPS: GalleryNavGroup[] = [
  {
    group: "通用",
    groupEn: "General",
    libraryId: "kibo-ui",
    items: [
      componentItem({
        id: "button",
        en: "Button",
        label: "按钮",
        summary: "触发即时操作，支持颜色、形态、加载、图标与链接用法。",
        keywords: ["anniu", "操作", "loading", "icon"],
        api: true,
      }),
      componentItem({ id: "button-group", en: "ButtonGroup", label: "按钮组" }),
      componentItem({
        id: "float-button",
        en: "FloatButton",
        label: "悬浮按钮",
        api: true,
      }),
      componentItem({ id: "typography", en: "Typography", label: "排版",
        api: true,
      }),
      componentItem({ id: "copy-button", en: "CopyButton", label: "复制按钮",
        api: true,
      }),
      componentItem({ id: "kbd", en: "Kbd", label: "快捷键",
        api: true,
      }),
      componentItem({ id: "label", en: "Label", label: "标签文本",
        api: true,
      }),
      componentItem({ id: "marker", en: "Marker", label: "标记",
        api: true,
      }),
    ],
  },
  {
    group: "布局",
    groupEn: "Layout",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "aspect-ratio", en: "AspectRatio", label: "宽高比",
        api: true,
      }),
      componentItem({ id: "direction", en: "Direction", label: "方向",
        api: true,
      }),
      componentItem({ id: "flex", en: "Flex", label: "弹性布局",
        api: true,
      }),
      componentItem({ id: "resizable", en: "Resizable", label: "可调整面板" }),
      componentItem({ id: "scroll-area", en: "ScrollArea", label: "滚动区域" }),
      componentItem({ id: "separator", en: "Separator", label: "分隔线",
        api: true,
      }),
      componentItem({ id: "sidebar", en: "Sidebar", label: "侧边栏" }),
      componentItem({ id: "space", en: "Space", label: "间距",
        api: true,
      }),
    ],
  },
  {
    group: "导航",
    groupEn: "Navigation",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "anchor", en: "Anchor", label: "锚点",
        api: true,
      }),
      componentItem({ id: "breadcrumb", en: "Breadcrumb", label: "面包屑",
        api: true,
      }),
      componentItem({
        id: "dropdown-menu",
        en: "DropdownMenu",
        label: "下拉菜单",
      }),
      componentItem({ id: "menubar", en: "Menubar", label: "菜单栏" }),
      componentItem({
        id: "navigation-menu",
        en: "NavigationMenu",
        label: "导航菜单",
      }),
      componentItem({ id: "pagination", en: "Pagination", label: "分页",
        api: true,
      }),
      componentItem({ id: "steps", en: "Steps", label: "步骤条",
        api: true,
      }),
      componentItem({ id: "tabs", en: "Tabs", label: "标签页" }),
    ],
  },
  {
    group: "数据录入",
    groupEn: "Data Entry",
    libraryId: "kibo-ui",
    items: [
      componentItem({
        id: "auto-complete",
        en: "AutoComplete",
        label: "自动完成",
        api: true,
      }),
      componentItem({ id: "cascader", en: "Cascader", label: "级联选择",
        api: true,
      }),
      componentItem({ id: "checkbox", en: "Checkbox", label: "多选框",
        api: true,
      }),
      componentItem({
        id: "color-picker",
        en: "ColorPicker",
        label: "颜色选择器",
        api: true,
      }),
      componentItem({ id: "combobox", en: "Combobox", label: "组合选择" }),
      componentItem({ id: "command", en: "Command", label: "命令面板" }),
      componentItem({
        id: "date-picker",
        en: "DatePicker",
        label: "日期选择框",
        api: true,
      }),
      componentItem({ id: "form-field", en: "FormField", label: "表单字段" }),
      componentItem({ id: "input", en: "Input", label: "输入框",
        api: true,
      }),
      componentItem({ id: "input-group", en: "InputGroup", label: "输入框组" }),
      componentItem({ id: "mentions", en: "Mentions", label: "提及",
        api: true,
      }),
      componentItem({
        id: "native-select",
        en: "NativeSelect",
        label: "原生选择",
        api: true,
      }),
      componentItem({ id: "radio-group", en: "RadioGroup", label: "单选组",
        api: true,
      }),
      componentItem({ id: "rate", en: "Rate", label: "评分",
        api: true,
      }),
      componentItem({ id: "select", en: "Select", label: "选择器" }),
      componentItem({ id: "slider", en: "Slider", label: "滑动输入条",
        api: true,
      }),
      componentItem({ id: "switch", en: "Switch", label: "开关",
        api: true,
      }),
      componentItem({
        id: "time-picker",
        en: "TimePicker",
        label: "时间选择框",
        api: true,
      }),
      componentItem({ id: "transfer", en: "Transfer", label: "穿梭框",
        api: true,
      }),
      componentItem({ id: "tree-select", en: "TreeSelect", label: "树选择",
        api: true,
      }),
    ],
  },
  {
    group: "数据展示",
    groupEn: "Data Display",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "accordion", en: "Accordion", label: "手风琴" }),
      componentItem({ id: "attachment", en: "Attachment", label: "附件" }),
      componentItem({ id: "avatar", en: "Avatar", label: "头像",
        api: true,
      }),
      componentItem({ id: "badge", en: "Badge", label: "徽标",
        api: true,
      }),
      componentItem({ id: "calendar", en: "Calendar", label: "日历",
        api: true,
      }),
      componentItem({ id: "card", en: "Card", label: "卡片" }),
      componentItem({ id: "carousel", en: "Carousel", label: "走马灯",
        api: true,
      }),
      componentItem({ id: "chart", en: "Chart", label: "图表",
        api: true,
      }),
      componentItem({ id: "chat-bubble", en: "ChatBubble", label: "聊天气泡" }),
      componentItem({
        id: "collapsible",
        en: "Collapsible",
        label: "折叠容器",
      }),
      componentItem({
        id: "descriptions",
        en: "Descriptions",
        label: "描述列表",
        api: true,
      }),
      componentItem({ id: "empty-state", en: "EmptyState", label: "空状态",
        api: true,
      }),
      componentItem({ id: "file-tree", en: "FileTree", label: "文件树",
        api: true,
      }),
      componentItem({ id: "hover-card", en: "HoverCard", label: "悬浮卡片" }),
      componentItem({ id: "image", en: "Image", label: "图片",
        api: true,
      }),
      componentItem({
        id: "link-preview",
        en: "LinkPreview",
        label: "链接预览",
        api: true,
      }),
      componentItem({ id: "list", en: "List", label: "列表",
        api: true,
      }),
      componentItem({ id: "list-item", en: "ListItem", label: "列表项" }),
      componentItem({ id: "popover", en: "Popover", label: "气泡卡片" }),
      componentItem({ id: "qr-code", en: "QRCode", label: "二维码",
        api: true,
      }),
      componentItem({ id: "statistic", en: "Statistic", label: "统计数值",
        api: true,
      }),
      componentItem({ id: "table", en: "Table", label: "表格",
        api: true,
      }),
      componentItem({ id: "tag", en: "Tag", label: "标签",
        api: true,
      }),
      componentItem({ id: "timeline", en: "Timeline", label: "时间轴",
        api: true,
      }),
      componentItem({ id: "tooltip", en: "Tooltip", label: "文字提示" }),
      componentItem({ id: "tree", en: "Tree", label: "树形控件",
        api: true,
      }),
    ],
  },
  {
    group: "反馈",
    groupEn: "Feedback",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "alert", en: "Alert", label: "警告提示",
        api: true,
      }),
      componentItem({
        id: "alert-dialog",
        en: "AlertDialog",
        label: "警告对话框",
      }),
      componentItem({ id: "dialog", en: "Dialog", label: "对话框" }),
      componentItem({ id: "drawer", en: "Drawer", label: "抽屉" }),
      componentItem({ id: "message", en: "Message", label: "全局提示" }),
      componentItem({
        id: "message-scroller",
        en: "MessageScroller",
        label: "消息滚动",
      }),
      componentItem({
        id: "notification",
        en: "Notification",
        label: "通知提醒",
        api: true,
      }),
      componentItem({
        id: "popconfirm",
        en: "Popconfirm",
        label: "气泡确认框",
      }),
      componentItem({ id: "progress", en: "Progress", label: "进度条",
        api: true,
      }),
      componentItem({ id: "result", en: "Result", label: "结果",
        api: true,
      }),
      componentItem({ id: "skeleton", en: "Skeleton", label: "骨架屏" }),
      componentItem({ id: "spin", en: "Spin", label: "加载中",
        api: true,
      }),
      componentItem({ id: "toaster", en: "Toaster", label: "吐司容器" }),
      componentItem({ id: "watermark", en: "Watermark", label: "水印",
        api: true,
      }),
    ],
  },
  {
    group: "其他",
    groupEn: "Other",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "affix", en: "Affix", label: "固钉",
        api: true,
      }),
      componentItem({ id: "border-beam", en: "BorderBeam", label: "边框流光",
        api: true,
      }),
      componentItem({
        id: "context-menu",
        en: "ContextMenu",
        label: "右键菜单",
      }),
      componentItem({ id: "sheet", en: "Sheet", label: "工作表" }),
      componentItem({ id: "toggle", en: "Toggle", label: "切换按钮",
        api: true,
      }),
      componentItem({
        id: "toggle-group",
        en: "ToggleGroup",
        label: "切换按钮组",
      }),
    ],
  },
  {
    group: "复合组件",
    groupEn: "Blocks",
    libraryId: "kibo-ui",
    items: [
      componentItem({ id: "announcement", en: "Announcement", label: "公告条",
        api: true,
      }),
      componentItem({ id: "avatar-stack", en: "AvatarStack", label: "头像堆叠" }),
      componentItem({ id: "avatar-tooltip-group", en: "AvatarTooltipGroup", label: "头像提示组" }),
      componentItem({ id: "banner", en: "Banner", label: "横幅",
        api: true,
      }),
      componentItem({ id: "calculator", en: "Calculator", label: "计算器",
        api: true,
      }),
      componentItem({ id: "choicebox", en: "Choicebox", label: "选择框" }),
      componentItem({ id: "code-block", en: "CodeBlock", label: "代码块" }),
      componentItem({ id: "code-panel", en: "CodePanel", label: "代码面板" }),
      componentItem({ id: "code-tabs", en: "CodeTabs", label: "代码标签页" }),
      componentItem({ id: "comparison", en: "Comparison", label: "对比滑块",
        api: true,
      }),
      componentItem({ id: "contribution-graph", en: "ContributionGraph", label: "贡献图",
        api: true,
      }),
      componentItem({ id: "credit-card", en: "CreditCard", label: "信用卡" }),
      componentItem({ id: "cursor-follow", en: "CursorFollow", label: "光标跟随" }),
      componentItem({ id: "data-table", en: "DataTable", label: "数据表格",
        api: true,
      }),
      componentItem({ id: "deck", en: "Deck", label: "卡片堆叠" }),
      componentItem({ id: "dialog-stack", en: "DialogStack", label: "对话框堆叠" }),
      componentItem({ id: "dropzone", en: "Dropzone", label: "拖拽上传",
        api: true,
      }),
      componentItem({ id: "editor", en: "Editor", label: "富文本编辑器" }),
      componentItem({ id: "feature-calendar", en: "FeatureCalendar", label: "功能日历" }),
      componentItem({ id: "gantt", en: "Gantt", label: "甘特图",
        api: true,
      }),
      componentItem({ id: "github-stars-wheel", en: "GitHubStarsWheel", label: "GitHub 星标",
        api: true,
      }),
      componentItem({ id: "glimpse", en: "Glimpse", label: "一瞥效果" }),
      componentItem({ id: "image-crop", en: "ImageCrop", label: "图片裁剪",
        api: true,
      }),
      componentItem({ id: "image-zoom", en: "ImageZoom", label: "图片缩放",
        api: true,
      }),
      componentItem({ id: "kanban", en: "Kanban", label: "看板",
        api: true,
      }),
      componentItem({ id: "marquee", en: "Marquee", label: "跑马灯",
        api: true,
      }),
      componentItem({ id: "masonry", en: "Masonry", label: "瀑布流",
        api: true,
      }),
      componentItem({ id: "mini-calendar", en: "MiniCalendar", label: "迷你日历",
        api: true,
      }),
      componentItem({ id: "pill", en: "Pill", label: "药丸标签" }),
      componentItem({ id: "presence-cursor", en: "PresenceCursor", label: "协作光标" }),
      componentItem({ id: "rating", en: "Rating", label: "评分组件" }),
      componentItem({ id: "reel", en: "Reel", label: "卷轴滑动",
        api: true,
      }),
      componentItem({ id: "relative-time", en: "RelativeTime", label: "相对时间",
        api: true,
      }),
      componentItem({ id: "sandbox", en: "Sandbox", label: "沙箱预览",
        api: true,
      }),
      componentItem({ id: "snippet", en: "Snippet", label: "代码片段" }),
      componentItem({ id: "spinner", en: "Spinner", label: "加载旋转",
        api: true,
      }),
      componentItem({ id: "status", en: "Status", label: "状态指示",
        api: true,
      }),
      componentItem({ id: "stories", en: "Stories", label: "快拍轮播" }),
      componentItem({ id: "tabs-motion", en: "TabsMotion", label: "动效标签页" }),
      componentItem({ id: "tags", en: "Tags", label: "标签组" }),
      componentItem({ id: "theme-switcher", en: "ThemeSwitcher", label: "主题切换",
        api: true,
      }),
      componentItem({ id: "ticker", en: "Ticker", label: "滚动条",
        api: true,
      }),
      componentItem({ id: "tooltip-motion", en: "TooltipMotion", label: "动效提示" }),
      componentItem({ id: "tour", en: "Tour", label: "引导漫游" }),
      componentItem({ id: "video-player", en: "VideoPlayer", label: "视频播放器",
        api: true,
      }),
    ],
  },
  {
    group: "文本动效",
    groupEn: "Text Animations",
    libraryId: "react-bits",
    items: [
      rbItem("glitch-text", "GlitchText", "故障文字"),
      rbItem("gradient-text", "GradientText", "渐变动画文字"),
      rbItem("rotating-text", "RotatingText", "旋转切换文字"),
      rbItem("scrambled-text", "ScrambledText", "乱码文字"),
      rbItem("scroll-float", "ScrollFloat", "滚动浮现文字"),
      rbItem("scroll-reveal", "ScrollReveal", "滚动揭示文字"),
      rbItem("scroll-velocity", "ScrollVelocity", "滚动速度文字"),
      rbItem("shiny-text", "ShinyText", "闪光文字"),
      rbItem("shuffle", "Shuffle", "字符洗牌"),
      rbItem("split-text", "SplitText", "文字拆分动画"),
      rbItem("text-cursor", "TextCursor", "文字光标拖尾"),
      rbItem("text-pressure", "TextPressure", "压力感文字"),
      rbItem("text-type", "TextType", "打字机文字"),
      rbItem("true-focus", "TrueFocus", "焦点文字"),
      rbItem("variable-proximity", "VariableProximity", "可变字体邻近感应"),
    ],
  },
  {
    group: "测试",
    groupEn: "Test",
    libraryId: "kibo-ui",
    items: [
      componentItem({
        id: "mdx-test",
        en: "MdxTest",
        label: "MDX 实验性测试页",
        summary:
          "测试排版、布局、数学公式、Markdown 内建代码块及高级 MDX 组件的渲染效果。",
        keywords: ["test", "mdx", "math", "code", "table"],
      }),
    ],
  },
{
  group: "Components",
  groupEn: "Components",
  libraryId: "react-bits",
  items: [
    rbItem("animated-list", "AnimatedList", "动画列表"),
    rbItem("border-glow", "BorderGlow", "边框发光"),
    rbItem("bounce-cards", "BounceCards", "弹跳卡片"),
    rbItem("bubble-menu", "BubbleMenu", "气泡菜单"),
    rbItem("card-nav", "CardNav", "卡片导航"),
    rbItem("card-swap", "CardSwap", "卡片交换"),
    rbItem("carousel-rb", "Carousel", "轮播"),
    rbItem("chroma-grid", "ChromaGrid", "色彩网格"),
    rbItem("circular-gallery", "CircularGallery", "环形画廊"),
    rbItem("counter", "Counter", "计数器"),
    rbItem("decay-card", "DecayCard", "衰减卡片"),
    rbItem("dock", "Dock", "Dock栏"),
    rbItem("dome-gallery", "DomeGallery", "穹顶画廊"),
    rbItem("elastic-slider", "ElasticSlider", "弹性滑块"),
    rbItem("flowing-menu", "FlowingMenu", "流动菜单"),
    rbItem("fluid-glass", "FluidGlass", "流体玻璃"),
    rbItem("flying-posters", "FlyingPosters", "飞行海报"),
    rbItem("folder", "Folder", "文件夹"),
    rbItem("glass-icons", "GlassIcons", "玻璃图标"),
    rbItem("glass-surface", "GlassSurface", "玻璃表面"),
    rbItem("gooey-nav", "GooeyNav", "粘性导航"),
    rbItem("infinite-menu", "InfiniteMenu", "无限菜单"),
    rbItem("lanyard", "Lanyard", "挂绳效果"),
    rbItem("magic-bento", "MagicBento", "魔法便当"),
    rbItem("masonry-rb", "Masonry", "瀑布流"),
    rbItem("model-viewer", "ModelViewer", "3D模型"),
    rbItem("pill-nav", "PillNav", "胶囊导航"),
    rbItem("pixel-card", "PixelCard", "像素卡片"),
    rbItem("profile-card", "ProfileCard", "个人卡片"),
    rbItem("reflective-card", "ReflectiveCard", "反射卡片"),
    rbItem("scroll-stack", "ScrollStack", "滚动堆叠"),
    rbItem("spotlight-card", "SpotlightCard", "聚光卡片"),
    rbItem("stack", "Stack", "堆叠"),
    rbItem("staggered-menu", "StaggeredMenu", "交错菜单"),
    rbItem("stepper", "Stepper", "步骤器"),
    rbItem("tilted-card", "TiltedCard", "倾斜卡片"),
  ],
},
{
  group: "Animations",
  groupEn: "Animations",
  libraryId: "react-bits",
  items: [
    rbItem("animated-content", "AnimatedContent", "动画内容"),
    rbItem("antigravity", "Antigravity", "反重力"),
    rbItem("blob-cursor", "BlobCursor", "斑点光标"),
    rbItem("click-spark", "ClickSpark", "点击火花"),
    rbItem("crosshair", "Crosshair", "十字准星"),
    rbItem("cubes", "Cubes", "立方体"),
    rbItem("electric-border", "ElectricBorder", "电光边框"),
    rbItem("fade-content", "FadeContent", "淡入内容"),
    rbItem("ghost-cursor", "GhostCursor", "幽灵光标"),
    rbItem("glare-hover", "GlareHover", "眩光悬浮"),
    rbItem("gradual-blur", "GradualBlur", "渐进模糊"),
    rbItem("image-trail", "ImageTrail", "图片拖尾"),
    rbItem("laser-flow", "LaserFlow", "激光流"),
    rbItem("logo-loop", "LogoLoop", "Logo循环"),
    rbItem("magic-rings", "MagicRings", "魔法圆环"),
    rbItem("magnet", "Magnet", "磁吸"),
    rbItem("magnet-lines", "MagnetLines", "磁吸线条"),
    rbItem("metaballs", "MetaBalls", "元球"),
    rbItem("metallic-paint", "MetallicPaint", "金属漆面"),
    rbItem("noise", "Noise", "噪点"),
    rbItem("orbit-images", "OrbitImages", "轨道图片"),
    rbItem("pixel-trail", "PixelTrail", "像素拖尾"),
    rbItem("pixel-transition", "PixelTransition", "像素过渡"),
    rbItem("ribbons", "Ribbons", "丝带"),
    rbItem("shape-blur", "ShapeBlur", "形状模糊"),
    rbItem("splash-cursor", "SplashCursor", "飞溅光标"),
    rbItem("star-border", "StarBorder", "星光边框"),
    rbItem("sticker-peel", "StickerPeel", "贴纸剥离"),
    rbItem("strands", "Strands", "缕线"),
    rbItem("target-cursor", "TargetCursor", "靶心光标"),
  ],
},
{
  group: "Backgrounds",
  groupEn: "Backgrounds",
  libraryId: "react-bits",
  items: [
    rbItem("aurora", "Aurora", "极光"),
    rbItem("balatro", "Balatro", "Balatro特效"),
    rbItem("ballpit", "Ballpit", "球池"),
    rbItem("beams", "Beams", "光束"),
    rbItem("color-bends", "ColorBends", "色彩弯曲"),
    rbItem("dark-veil", "DarkVeil", "暗幕"),
    rbItem("dither", "Dither", "抖动"),
    rbItem("dot-field", "DotField", "点阵场"),
    rbItem("dot-grid", "DotGrid", "点阵网格"),
    rbItem("evil-eye", "EvilEye", "邪眼"),
    rbItem("faulty-terminal", "FaultyTerminal", "故障终端"),
    rbItem("ferrofluid", "Ferrofluid", "磁流体"),
    rbItem("floating-lines", "FloatingLines", "浮动线条"),
    rbItem("galaxy", "Galaxy", "星系"),
    rbItem("gradient-blinds", "GradientBlinds", "渐变百叶窗"),
    rbItem("grainient", "Grainient", "颗粒渐变"),
    rbItem("grid-distortion", "GridDistortion", "网格扭曲"),
    rbItem("grid-motion", "GridMotion", "网格运动"),
    rbItem("grid-scan", "GridScan", "网格扫描"),
    rbItem("hyperspeed", "Hyperspeed", "超速"),
    rbItem("iridescence", "Iridescence", "虹彩"),
    rbItem("letter-glitch", "LetterGlitch", "字母故障"),
    rbItem("lightfall", "Lightfall", "光落"),
    rbItem("lightning", "Lightning", "闪电"),
    rbItem("light-pillar", "LightPillar", "光柱"),
    rbItem("light-rays", "LightRays", "光线"),
    rbItem("line-waves", "LineWaves", "线波"),
    rbItem("liquid-chrome", "LiquidChrome", "液态铬"),
    rbItem("liquid-ether", "LiquidEther", "液态以太"),
    rbItem("orb", "Orb", "球体"),
    rbItem("particles", "Particles", "粒子"),
    rbItem("pixel-blast", "PixelBlast", "像素爆炸"),
    rbItem("pixel-snow", "PixelSnow", "像素雪花"),
    rbItem("plasma", "Plasma", "等离子体"),
    rbItem("plasma-wave", "PlasmaWave", "等离子波"),
    rbItem("prism", "Prism", "棱镜"),
    rbItem("prismatic-burst", "PrismaticBurst", "棱镜爆发"),
    rbItem("radar", "Radar", "雷达"),
    rbItem("ripple-grid", "RippleGrid", "波纹网格"),
    rbItem("shape-grid", "ShapeGrid", "形状网格"),
    rbItem("side-rays", "SideRays", "侧射线"),
    rbItem("silk", "Silk", "丝绸"),
    rbItem("soft-aurora", "SoftAurora", "柔光极光"),
    rbItem("threads", "Threads", "线缕"),
    rbItem("waves", "Waves", "波浪"),
  ],
},
{
  group: "TextAnimations",
  groupEn: "TextAnimations",
  libraryId: "react-bits",
  items: [
    rbItem("ascii-text", "ASCIIText", "ASCII文本"),
    rbItem("blur-text", "BlurText", "模糊文本"),
    rbItem("circular-text", "CircularText", "环形文本"),
    rbItem("count-up", "CountUp", "数字递增"),
    rbItem("curved-loop", "CurvedLoop", "曲线循环"),
    rbItem("decrypted-text", "DecryptedText", "解密文本"),
    rbItem("falling-text", "FallingText", "坠落文本"),
    rbItem("fuzzy-text", "FuzzyText", "模糊文本"),
    rbItem("glitch-text", "GlitchText", "故障文本"),
    rbItem("gradient-text", "GradientText", "渐变文本"),
    rbItem("rotating-text", "RotatingText", "旋转文本"),
    rbItem("scrambled-text", "ScrambledText", "乱码文本"),
    rbItem("scroll-float", "ScrollFloat", "滚动浮起"),
    rbItem("scroll-reveal", "ScrollReveal", "滚动揭示"),
    rbItem("scroll-velocity", "ScrollVelocity", "滚动速度"),
    rbItem("shiny-text", "ShinyText", "闪光文本"),
    rbItem("shuffle", "Shuffle", "洗牌"),
    rbItem("split-text", "SplitText", "分裂文本"),
    rbItem("text-cursor", "TextCursor", "文本光标"),
    rbItem("text-pressure", "TextPressure", "文本压力"),
    rbItem("text-type", "TextType", "打字效果"),
    rbItem("true-focus", "TrueFocus", "真实聚焦"),
    rbItem("variable-proximity", "VariableProximity", "可变邻近"),
  ],
},
  {
    group: "图表",
    groupEn: "Charts",
    libraryId: "bklit-ui",
    items: [
      bklitItem("area-chart", "AreaChart", "面积图"),
      bklitItem("bar-chart", "BarChart", "柱状图"),
      bklitItem("candlestick-chart", "CandlestickChart", "K线图"),
      bklitItem("composed-chart", "ComposedChart", "组合图"),
      bklitItem("funnel-chart", "FunnelChart", "漏斗图"),
      bklitItem("gauge", "Gauge", "仪表盘"),
      bklitItem("line-chart", "LineChart", "折线图"),
      bklitItem("live-line-chart", "LiveLineChart", "实时折线图"),
      bklitItem("pie-chart", "PieChart", "饼图"),
      bklitItem("radar-chart", "RadarChart", "雷达图"),
      bklitItem("ring-chart", "RingChart", "环形图"),
      bklitItem("scatter-chart", "ScatterChart", "散点图"),
    ],
  },
  {
    group: "高级图表",
    groupEn: "Advanced Charts",
    libraryId: "bklit-ui",
    items: [
      bklitItem("choropleth-chart", "ChoroplethChart", "等值区域图"),
      bklitItem("heatmap-chart", "HeatmapChart", "热力图"),
      bklitItem("sankey-chart", "SankeyChart", "桑基图"),
    ],
  },
  {
    group: "图表工具",
    groupEn: "Chart Tools",
    libraryId: "bklit-ui",
    items: [
      bklitItem("chart-tooltip", "ChartTooltip", "图表提示框"),
      bklitItem("legend", "Legend", "图例"),
      bklitItem("chart-grid", "ChartGrid", "图表网格"),
      bklitItem("chart-brush", "ChartBrush", "图表刷选"),
    ],
  },
  {
    group: "动画",
    groupEn: "Animation",
    libraryId: "bklit-ui",
    items: [
      bklitItem("fan-circles", "FanCircles", "扇形扩散"),
    ],
  },
  {
    group: "图表",
    groupEn: "Charts",
    libraryId: "evilcharts",
    items: [
      evilItem("bar-chart", "EvilBarChart", "柱状图"),
      evilItem("line-chart", "EvilLineChart", "折线图"),
      evilItem("area-chart", "EvilAreaChart", "面积图"),
      evilItem("pie-chart", "EvilPieChart", "饼图"),
      evilItem("composed-chart", "EvilComposedChart", "组合图"),
      evilItem("radar-chart", "EvilRadarChart", "雷达图"),
      evilItem("radial-chart", "EvilRadialChart", "径向图"),
      evilItem("sankey-chart", "EvilSankeyChart", "桑基图"),
    ],
  },
  {
    group: "图表工具",
    groupEn: "Chart Tools",
    libraryId: "evilcharts",
    items: [
      evilItem("chart", "ChartContainer", "图表容器"),
      evilItem("brush", "EvilBrush", "刷选工具"),
    ],
  },
  {
    group: "组件",
    groupEn: "Components",
    libraryId: "sabraman",
    items: [
      sabramanItem("roundbit", "RoundbitFrame", "圆角框架"),
      sabramanItem("bar-button", "LegacyBarButton", "工具栏按钮"),
      sabramanItem("segmented-control", "LegacySegmentedControl", "分段控件"),
      sabramanItem("switch", "LegacySwitch", "开关"),
      sabramanItem("slider", "LegacySlider", "滑块"),
      sabramanItem("clock", "LegacyClock", "时钟"),
      sabramanItem("notification", "LegacyNotification", "通知"),
      sabramanItem("alert-dialog", "LegacyAlertDialog", "警告对话框"),
      sabramanItem("code-block", "LegacyCodeBlockCommand", "代码块命令"),
    ],
  },
  {
    group: "编辑器",
    groupEn: "Editor",
    libraryId: "plate",
    items: [
      {
        id: "editors-showcase",
        label: "编辑器展示",
        en: "PlateEditorsShowcase",
        to: "/components/plate/editors-showcase",
        summary: "Plate 富文本编辑器展示组件。",
        keywords: ["plate", "editor", "showcase"],
        antd: false,
        migration: 0,
        api: true,
      },
    ],
  },
  {
    group: "布局",
    groupEn: "Layout",
    libraryId: "uselayouts",
    items: [
      uselayoutsItem("3d-book", "3dBook", "3D 书"),
      uselayoutsItem("animated-collection", "AnimatedCollection", "动画集合"),
      uselayoutsItem("bento-card", "BentoCard", "便当卡片"),
      uselayoutsItem("bottom-menu", "BottomMenu", "底部菜单"),
      uselayoutsItem("bucket", "Bucket", "存储桶"),
      uselayoutsItem("day-picker", "DayPicker", "日期选择"),
      uselayoutsItem("delete-button", "DeleteButton", "删除按钮"),
      uselayoutsItem("discover-button", "DiscoverButton", "发现按钮"),
      uselayoutsItem("discrete-tabs", "DiscreteTabs", "离散标签"),
      uselayoutsItem("dynamic-toolbar", "DynamicToolbar", "动态工具栏"),
      uselayoutsItem("empty-testimonial", "EmptyTestimonial", "空推荐"),
      uselayoutsItem("expandable-gallery", "ExpandableGallery", "可扩展画廊"),
      uselayoutsItem("feature-carousel", "FeatureCarousel", "特性轮播"),
      uselayoutsItem("fluid-expanding-grid", "FluidExpandingGrid", "流体网格"),
      uselayoutsItem("folder-interaction", "FolderInteraction", "文件夹交互"),
      uselayoutsItem("inline-edit", "InlineEdit", "内联编辑"),
      uselayoutsItem("magnified-bento", "MagnifiedBento", "放大便当"),
      uselayoutsItem("morphing-input", "MorphingInput", "变形输入"),
      uselayoutsItem("multi-step-form", "MultiStepForm", "多步表单"),
      uselayoutsItem("pricing-card", "PricingCard", "定价卡片"),
      uselayoutsItem("shake-testimonial-card", "ShakeTestimonialCard", "抖动推荐卡"),
      uselayoutsItem("smooth-dropdown", "SmoothDropdown", "平滑下拉"),
      uselayoutsItem("stacked-list", "StackedList", "堆叠列表"),
      uselayoutsItem("status-button", "StatusButton", "状态按钮"),
      uselayoutsItem("vertical-tabs", "VerticalTabs", "垂直标签"),
    ],
  },

]

const genericComponentToc = [
  { id: "when-to-use", title: "何时使用", depth: 2 },
  { id: "examples", title: "代码演示", depth: 2 },
  { id: "api", title: "API", depth: 2 },
  { id: "faq", title: "常见问题", depth: 2 },
  { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
  { id: "source", title: "源码", depth: 2 },
] satisfies GalleryTocItem[]

const defaultDocs = Object.fromEntries(
  GALLERY_NAV_GROUPS.flatMap((group) =>
    group.items.map((item) => [
      item.id,
      {
        title: item.label,
        en: item.en,
        description: item.summary,
        toc: genericComponentToc,
      } satisfies GalleryDocMeta,
    ])
  )
)

export const GALLERY_DOCS: Record<string, GalleryDocMeta> = {
  ...defaultDocs,
  button: {
    title: "按钮",
    en: "Button",
    description:
      "用于触发即时操作，支持颜色、变体、尺寸、形状、图标、加载与链接用法。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "button", title: "基础按钮", depth: 3 },
      { id: "variants", title: "颜色与变体", depth: 3 },
      { id: "icon", title: "图标按钮", depth: 3 },
      { id: "size", title: "按钮尺寸", depth: 3 },
      { id: "shape", title: "按钮形状", depth: 3 },
      { id: "disabled", title: "不可用状态", depth: 3 },
      { id: "loading", title: "加载中状态", depth: 3 },
      { id: "ghost", title: "幽灵按钮", depth: 3 },
      { id: "block", title: "Block 按钮", depth: 3 },
      { id: "link", title: "链接与路由", depth: 3 },
      { id: "group", title: "按钮组合", depth: 3 },
      { id: "motion", title: "动效控制", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  breadcrumb: {
    title: "面包屑",
    en: "Breadcrumb",
    description: "显示当前页面在系统层级结构中的位置。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "breadcrumb", title: "基础用法", depth: 3 },
      { id: "routes", title: "路由生成", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  "button-group": {
    title: "按钮组",
    en: "ButtonGroup",
    description: "将多个按钮紧凑排列为一个视觉整体。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "button-group", title: "基础组合", depth: 3 },
      { id: "form", title: "表单与方向", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  "float-button": {
    title: "悬浮按钮",
    en: "FloatButton",
    description: "悬浮于页面内容上方，提供快捷操作入口。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "float-button", title: "基础用法", depth: 3 },
      { id: "badge", title: "角标", depth: 3 },
      { id: "group", title: "按钮组", depth: 3 },
      { id: "back-top", title: "回到顶部", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  kbd: {
    title: "键盘按键",
    en: "Kbd",
    description: "展示键盘按键或快捷键组合。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "kbd", title: "基础用法", depth: 3 },
      { id: "group", title: "按键组合", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  typography: {
    title: "排版",
    en: "Typography",
    description: "提供文本排版能力：Text、Title、Paragraph 和 Link。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "typography-text", title: "行内文本", depth: 3 },
      { id: "typography-title", title: "标题", depth: 3 },
      { id: "typography-paragraph", title: "段落与链接", depth: 3 },
      { id: "typography-copyable", title: "可复制", depth: 3 },
      { id: "typography-ellipsis", title: "溢出省略", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  input: {
    title: "输入框",
    en: "Input",
    description: "基础表单控件，支持前后缀、清除、校验、尺寸和 TextArea。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "input", title: "基础用法", depth: 3 },
      { id: "sizes", title: "尺寸与变体", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  table: {
    title: "表格",
    en: "Table",
    description: "展示结构化行列数据，支持表头、表体和状态单元格。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "table", title: "基础用法", depth: 3 },
      { id: "states", title: "完整数据展示", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  select: {
    title: "选择器",
    en: "Select",
    description: "下拉选择器，支持单选、多选、标签、搜索和分组。",
    toc: [
      { id: "when-to-use", title: "何时使用", depth: 2 },
      { id: "examples", title: "代码演示", depth: 2 },
      { id: "select", title: "基础用法", depth: 3 },
      { id: "groups", title: "分组与尺寸", depth: 3 },
      { id: "api", title: "API", depth: 2 },
      { id: "faq", title: "常见问题", depth: 2 },
      { id: "llm-rules", title: "LLM 使用规则", depth: 2 },
      { id: "source", title: "源码", depth: 2 },
    ],
  },
  "mdx-test": {
    title: "MDX 实验性测试页",
    en: "MdxTest",
    description:
      "用于测试排版、布局、数学公式、Markdown 内建代码块及高级 MDX 组件的渲染效果。",
    toc: [
      { id: "introduction", title: "一、 导言", depth: 2 },
      { id: "typography-and-layout", title: "二、 排版与布局测试", depth: 2 },
      { id: "math-formulas", title: "三、 数学公式渲染 (LaTeX)", depth: 2 },
      { id: "code-blocks", title: "四、 代码块展示", depth: 2 },
      { id: "tables-and-diagrams", title: "五、 学术三线表与图表", depth: 2 },
      { id: "conclusion", title: "六、 结论", depth: 2 },
    ],
  },
}

export const gallerySearchEntries = GALLERY_NAV_GROUPS.flatMap((group) =>
  group.items.map((item) => ({
    ...item,
    group: group.group,
    groupEn: group.groupEn,
  }))
)

export const galleryItemCount = GALLERY_NAV_GROUPS.reduce(
  (total, group) => total + group.items.length,
  0
)
